
format = """$sudo\
            $username\
            $hostname\
            $directory\
            $custom\
            $git_branch\
            \n\
            $character\
"""

right_format = """$git_status\
                  $python\
"""


add_newline = true

[line_break]
disabled = true

[sudo]
format = "[$symbol]($style)"
style = "bold red"
symbol = "! "
disabled = false

[username]
format = "[$user]($style)@"
style_user = "yellow"
style_root = "bold red"
show_always = true

[hostname]
format = "[$hostname]($style) in "
style = "yellow"
trim_at = "-"
ssh_only = false
disabled = false

[directory]
style = "purple"
truncation_length = 0
truncate_to_repo = false
truncation_symbol = "repo: "

[git_status]
style = "white"
ahead = "⇡${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
behind = "⇣${count}"
deleted = "x"

[cmd_duration]
min_time = 1
format = "took [$duration]($style)"
disabled = false


[time]
format = "$time($style)"
time_format = "%T"
style = "bright-white"
disabled = false

[character]
success_symbol = " [λ](dimmed blue)"
error_symbol = " [×](bold red)"

# SYMBOLS
[status]
symbol = "🔴"
format = '[\[$symbol$status_common_meaning$status_signal_name$status_maybe_int\]]($style)'
map_symbol = true
disabled = false

[aws]
disabled = false
symbol = " "

[conda]
disabled = false
symbol = " "

[dart]
disabled = false
symbol = " "

[docker_context]
disabled = false
symbol = " "

[elixir]
disabled = false
symbol = " "

[elm]
disabled = false
symbol = " "

[git_branch]
format = "[$symbol$branch]($style)"
disabled = false
symbol = " "

[golang]
disabled = false
symbol = " "

[hg_branch]
disabled = false
symbol = " "

[java]
disabled = false
symbol = " "

[julia]
disabled = false
symbol = " "

[nim]
disabled = false
symbol = " "

[nix_shell]
disabled = false
symbol = " "

[nodejs]
disabled = false
symbol = " "

[package]
disabled = false
symbol = " "

[perl]
disabled = false
symbol = " "

[php]
disabled = false
symbol = " "

[python]
format = "[$symbol$pyenv_prefix($version )($virtualenv) ]($style)"
disabled = false
symbol = " "

[ruby]
disabled = false
symbol = " "

[rust]
disabled = false
symbol = " "

[swift]
disabled = false
symbol = "ﯣ "

[dotnet]
disabled = false
symbol = " "

[custom.symlink]
command = 'p=$(pwd); r=$(pwd -P); [ "$p" != "$r" ] && echo "󱅶 (${r/#$HOME/~})" || true'
when = "true"
format = "[$output]($style) "
style = "dimmed"
shell = ["zsh", "-d", "-f"]
